### PR TITLE
Design phase zero

### PR DESCRIPTION
**Pull request by lucsoft**
It will be a mocked UI just to implement all the components that will be used

### CODE REVIEW

**Comment by kanpov** [comment]
Are you going to implement the entire mocked UI in this PR or just the homepage?

Thanks for your work btw.

**Comment by kanpov** [comment]
Also, in `modpackBackground.kt`, please make sure to add support for as many Minecraft versions as possible, not just 1.16 and 1.17 since we're making support for Forge, Fabric and Quilt (_maybe_ LiteLoader and Rift, not a priority right now).

Versions below 1.12.2 are not a priority, though 1.7.10 would be nice.

**Comment by lucsoft** [comment]
> Also, in `modpackBackground.kt`, please make sure to add support for as many Minecraft versions as possible, not just 1.16 and 1.17 since we're making support for Forge, Fabric and Quilt (_maybe_ LiteLoader and Rift, not a priority right now).
> 
> Versions below 1.12.2 are not a priority, though 1.7.10 would be nice.

Its only for vanilla major versions other modloaders get the default background image or a custom one

**Comment by lucsoft** [comment]
> Are you going to implement the entire mocked UI in this PR or just the homepage?
> 
> Thanks for your work btw.

Only the major ui stuff:
- [ ] Login
- [ ] Home 
- [ ] Settings

**Comment by kanpov** [comment]
> Its only for vanilla major versions other modloaders get the default background image or a custom one

1.12.2 is a major version, especially since we're planning on supporting CurseForge format.
Undermining the Forge community is a bad idea in my opinion.

**Comment by lucsoft** [comment]
> Undermining the Forge community is a bad idea in my opinion.

Okay yeah good point i will ignore the mod loader for the default

> 1.12.2 is a major version, especially since we're planning on supporting CurseForge format.

Well adding more versions is not hard. We can add more later

**Comment by lucsoft** [comment]
Duplicate of #7

**Pull request closed without merging**
