### PR TITLE
Create a custom launcher core

### PR DESCRIPTION
**Pull request by kanpov**
The previous plan was to use [GJMLC](https://github.com/GoodTimeStudio/GoodTime-Java-Minecraft-Launcher-Core) as a launcher core in this app, but it has some issues which have driven me to the conclusion of making our own launcher:

- **It is no longer supported**. The repository hasn't been receiving any sort of updates since 2016
- **It is not on Maven Central**. This makes depending on it hard (previously we just inlined the entire code into a new package)
- **It is outdated**. Some parsing methods do not apply to the newest Mojang launcher formats, so a rework would be necessary anyway
- **It has bad code quality**. The core would need some cleaning up before it's code becomes good
- **It is written in Java**. As you may know, this project is fully in Kotlin, and adopting a Java library (especially a core component for the app to function correctly) is a bad idea, even though the interoperability works.
- Most importantly, **it only supports legacy launcher formats**, which means that a huge rework for that would also be needed if we had decided to stick with GJMLC.

I cannot give any estimates on when this will be ready, and there will likely be conflicts with `design-phase-zero` branch.

### CODE REVIEW

**Review by lucsoft — APPROVED** [review]

**Comment by kanpov** [comment]
This PR is almost done.

Fabric, Forge, Quilt, profiles etc will come in other PRs.

All that's left to do is fix the launching system and add support for authentication.

**Comment by RedGrapefruit09** [comment]
I'm back to working on this again.

I got badly poisoned yesterday and I'm currently recovering from it.
I'm not on my main workstation, but I can still develop this PR further.

**Comment by kanpov** [comment]
Minecraft launches now.

Auth, assets and asset indexes are the only things left to implement.

**Comment by kanpov** [comment]
This PR is almost ready for merge.

Waiting a bit for the CI to finish and merging it.

**Pull request merged**
